# Generated by Django 3.2.5 on 2021-07-30 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('names', models.CharField(max_length=1000)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_rating', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discount_per', models.IntegerField(default=0)),
                ('links', models.URLField(null=True)),
            ],
            options={
                'db_table': 'Scraped Data',
            },
        ),
    ]
