# Generated by Django 3.2.5 on 2021-07-31 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0002_scraped_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('categories', models.CharField(max_length=255)),
                ('names', models.CharField(max_length=1000)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_rating', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('links', models.URLField(null=True)),
            ],
            options={
                'db_table': 'Fast Scraped Data',
            },
        ),
    ]
