# Generated by Django 3.2.5 on 2021-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0004_alter_fastscraped_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraped',
            name='names',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
